package actors.cluster

import actors.monitor.MonitorProtocol.MonitorCommand
import akka.actor.Address
import akka.actor.typed.ActorRef
import akka.cluster.ClusterEvent.{MemberRemoved, MemberUp, ReachableMember, UnreachableMember}

/**
 * Defines the internal protocol of messages handled by cluster behavior.
 */
object ClusterProtocol:

  /**
   * Base trait for all commands handled by the ClusterManager actor.
   *
   * This protocol includes cluster membership events, application-level
   * commands, and internal lifecycle signals.
   */
  sealed trait ClusterMemberCommand

  /**
   * Marker trait for cluster membership events originating from Akka Cluster.
   *
   * These messages represent changes in the cluster topology and are
   * typically derived from Akka Cluster domain events.
   */
  sealed trait NodeEvent extends ClusterMemberCommand

  /**
   * Wraps an Akka Cluster [[MemberUp]] for internal handling.
   *
   * @param node
   * The original cluster member event.
   */
  final case class NodeUp(node: MemberUp) extends NodeEvent

  /**
   * Wraps an Akka Cluster [[MemberRemoved]] for internal handling.
   *
   * @param node
   * The original cluster member event.
   */
  final case class NodeRemoved(node: MemberRemoved) extends NodeEvent

  /**
   * Signals that a previously unreachable cluster member has become reachable again.
   *
   * @param node the cluster member that is now reachable
   */
  final case class NodeReachable(node: ReachableMember) extends NodeEvent

  /**
   * Wraps an Akka Cluster [[UnreachableMember]] for internal handling.
   *
   * @param node
   * The original cluster member event.
   */
  final case class NodeUnreachable(node: UnreachableMember) extends NodeEvent

  /**
   * Application-level commands used to control the behavior of the ClusterManager.
   *
   * These messages are generated by application actors during the system bootstrap or runtime.
   */
  sealed trait AppClusterCommand extends ClusterMemberCommand

  /**
   * Signals that the cluster simulation should start.
   */
  case object StartSimulation extends AppClusterCommand

  /**
   * Signals that the cluster simulation should stop.
   */
  case object StopSimulation extends AppClusterCommand

  /**
   * Registers the MonitorActor used to observe cluster-level events.
   *
   * @param ref reference to the MonitorActor
   */
  final case class RegisterMonitor(ref: ActorRef[MonitorCommand]) extends AppClusterCommand

  /**
   * Internal lifecycle and timeout events used by the ClusterManager
   * to manage time-based transitions and failure handling.
   *
   * These messages are never sent by external actors.
   */
  sealed trait InternalEvent extends ClusterMemberCommand

  /**
   * Signals the end of the time within which to successfully join the cluster.
   */
  case object JoinTimeout extends InternalEvent

  /**
   * Signals the end time from which a node is considered no longer recoverable.
   *
   * @param node the node no longer recoverable.
   */
  final case class UnreachableTimeout(node: Address) extends InternalEvent

  /**
   * Signals the end time from which the Seed is considered no longer recoverable.
   */
  case object SeedUnreachableTimeout extends InternalEvent
