package domain.data.sampling

import domain.data.Point2D
import domain.data.pattern.{ParametricCurve, SpiralCurve}
import domain.data.util.{Distribution, Space}


/**
 * Implements [[PointSampler]], it generates 2d points by sampling a parametric curve.
 *
 * The parameter is generated by a given distribution.
 *
 * @param curve                 the curve to be sampled
 * @param parameterDistribution a function that generates the curve's parameters
 */
private final case class CurveSampler(
  curve: ParametricCurve,
  parameterDistribution: () => Double
) extends PointSampler:

  /**
   * Applies a generated parameter to the given curve.
   *
   *  @return a 2d point
   */
  override def sample(): Point2D = curve.at(parameterDistribution())

/**
 * Factory for creating samplers specific to each curve type.
 */
object CurveSampler:

  /**
   * Creates a sampler for a [[SpiralCurve]].
   *
   * The spiral domain is computed using [[SpiralDomain]],
   * the parameter is computed using the given distribution.
   *
   * @param curve        the spiral
   * @param distribution the distribution used to generate the parameters
   * @param space        the space in which the curve is defined
   * @return a [[CurveSampler]]
   */
  def spiralSampler(
    curve: SpiralCurve,
    distribution: Distribution
  )(using Space): CurveSampler =
    val domain = SpiralDomain.domain(curve)
    CurveSampler(
      curve,
      () => distribution.sample(domain)
    )